name: color_swatch_generator
description: A Dart package to generate MaterialColor swatches from hex color codes.
version: 1.0.0
repository: https://github.com/guilherme-paiva2007/color_swatch_generator

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  material_color_utilities: ^0.13.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  color_swatch: color_swatch_generator